### ISSUE TITLE
Recognizing new levels or updating statistics

### ISSUE THREAD

**Issue by MYCRAFTisbest** [triwave/MakersofMario#10]
Site has trouble querying new levels automatically. Entering the level code manually forces the site to update with a level if it did not exist prior. Star count does not appear to update when reloading, not certain if this happens on a daily basis or something of the sort.

**Comment by jaku** [comment]
Levels are updated on a timer. We are importing many levels right now and as more users use the site levels will automatically get put into the site and then inserted into a queue that will update levels automatically though-out the day. Just isn't feasible to go out and ask for a new level update on every request. However we are working on a way to ensure this gets updated faster.

**Comment by MYCRAFTisbest** [comment]
I think something like viewing a user should check to see if that user has any new levels to display. Not sure how much site traffic you are expecting to see and how much you can actually support, but it seems like a viable solution.

**Comment by jaku** [comment]
The biggest issue is for every level we go to get data on, it takes 2+ seconds from Nintendo to get the data. Doing this would cause an overall feeling of "slow" to our own site while increasing the amount of traffic to Nintendo by a whole lot. We have a lot of ideas and have a system in the works to speed up the level stats to make this more current without causing the speed issues.
