### ISSUE TITLE
View in Navigation

### ISSUE THREAD

**Issue by MYCRAFTisbest** [triwave/MakersofMario#11]
While viewing a level or world, in the page navigation (the links to Home, Worlds, ECT.) is a link to View. Worlds/view gives a 404 page while levels/view tries to load up a level (presumably with a blank level code) and returns an error dialog about not finding said level.

**Comment by triwave** [comment]
Alright, this should be fixed.

The following links will redirect you to levels, races or worlds depending:
levels/view
races/view (wink wink)
worlds/view

Added some logic to the levels page to check for properly formatted level codes and force them to upper case to prevent API from pulling data as well.

**Comment by MYCRAFTisbest** [comment]
profiles/view Kappa
