### ISSUE TITLE
API - Tag System

### ISSUE THREAD

**Issue by MYCRAFTisbest** [triwave/MakersofMario#12]
The current level/world tag system allows any individual to tag any level or world with anything besides banned words like "shit" but at the same time "shit1" is valid. Also while "shitfuck" is invalid "shitfuckfuck" is valid. If I was a troll, I could, for instance, go to all of Panga's levels and tag them "fuckyoupanga" and it would be valid.

**Comment by aphex** [comment]
not sure this is a bug, @jaku maybe re-label this and we can table for a discussion on how to handle trolling. Remember at anytime someone could delete stupid labels.

**Comment by jaku** [comment]
Yeah, this is more of an enhancement. If we are able to have the filter match for anything in the filter and not just exact matches that is fine. But perhaps we even allow just locking of tags by level instead of individual tag locking. Will discuss and come up with a plan.
