### ISSUE TITLE
Creating Worlds Flow and Additional Features

### ISSUE THREAD

**Issue by jaku** [triwave/MakersofMario#18]
When you submit a new world, it should redirect you to the world page. A similar search function for levels should also exist on a page allowing you to add levels directly from there.

Remove "published" drop down on created level and make a button on the page to publish. Once published a worlds level list cannot be changed or re-ordered and cannot be unpublished.

**Comment by triwave** [comment]
Did some research on this:
- Published has been removed from the form
- The API is not returning the inserted id, we will need chud to handle this part.

**Comment by triwave** [comment]
Also, we should implement the other features before starting this request:
- Ordering levels
- Deleting a world (non published)
- Preventing duplicate levels

**Comment by jaku** [comment]
Added searching for levels and adding levels to worlds page.

;)

**Comment by jaku** [comment]
Also changed published to 1 for all new worlds currently. So that people can at least create worlds. Will add additional functionality laters.

**Comment by jaku** [comment]
Additional Feature we should add to the worlds page.

Instead of clicking on the level name and going to the level page. It should do a drop down showing the images and stats of the level. Along with a way to go directly to the level page. But this would look really nice and give the ability for the user to see the exact type of level as they are browsing world lists.

**Comment by jaku** [comment]
Need to rewrite some of the worlds page. A lot of things are not loading in the correct order so sometimes the creator doesn't get the correct functions loaded.

Like search and edit.

**Comment by jaku** [comment]
This is pretty much working now.

Ordering is a bigger thing that we will look into later. but deleting worlds is good now and dupe levels i think might be something we do UI wise.
