### ISSUE TITLE
Login / Logout Issues

### ISSUE THREAD

**Issue by triwave** [triwave/MakersofMario#2]
Issue stemming from session creation.  Expiration times are not syncing properly with the front end.

**Comment by jaku** [comment]
Issues related to MyCraft is with some JS loading. Similar errors to mobile issues. Will need to look into further.

utility.js:6 Uncaught TypeError: Cannot read property 'mouse' of undefined(anonymous function) @ utility.js:6(anonymous function) @ utility.js:6
/new5222016/#:1 Mixed Content: The page at 'https://makersofmario.com/new5222016/#' was loaded over HTTPS, but requested an insecure image 'http://mii-images.cdn.nintendo.net/wsnscapy7l16_normal_face.png'. This content should also be served over HTTPS.

main.js:34 Uncaught TypeError: $(...).nanoScroller is not a function

**Comment by jaku** [comment]
I believe this is resolved. Waiting on MyCraft to confirm.
