### ISSUE TITLE
API - Description for Levels not updating

### ISSUE THREAD

**Issue by jaku** [triwave/MakersofMario#25]
Post is correct, but query is invalid. Maybe the timer field?

{"success":false,"error":{"message":"Database query error.","code":510,"reference":"ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'"}}

**Comment by aphex** [comment]
Unable to reproduce. Please provide a test case, request headers.

Tested with
POST /level/?method=setMeta HTTP/1.1
 HOST: localhost:8080
 content-type: application/x-www-form-urlencoded
 content-length: 100

 hash=REMOVED&levelID=B7B7-0000-024D-12FD&description=This is a test

**Comment by jaku** [comment]
Appears to be on frontend side. Fixed.
