### ISSUE TITLE
API & FrontEnd - Tags over certain length cannot be removed.

### ISSUE THREAD

**Issue by jaku** [triwave/MakersofMario#29]
Should limit tags to about 12 characters on the backend.

**Comment by triwave** [comment]
Front end is complete.  I have prevented more than 12 characters within the HTML and javascript.

**Comment by triwave** [comment]
Confirmed, the world tags and level tags fields within the db are a maximum of 15 characters

**Comment by jaku** [comment]
Let's change it to like 12 in the DB then?
