### ISSUE TITLE
Direct Level Import

### ISSUE THREAD

**Issue by triwave** [triwave/MakersofMario#3]
Occasionally a level will not import into our database when accessing the associated levels/view/[code] page directly.

**Comment by jaku** [comment]
Please provide a level that this does not work on.

**Comment by triwave** [comment]
Waiting for Ethan to provide.

**Comment by triwave** [comment]
F843-0000-0246-C86A

He states that it finally did grab the information.  Not sure if there is a delay and or if there was an error.

**Comment by jaku** [comment]
Looks like a fluke perhaps. Cannot reproduce.
