### ISSUE TITLE
Duplicate messages inserted when clicking between tabs quickly.

### ISSUE THREAD

**Issue by FeFNiR104** [triwave/MakersofMario#31]
observed on the lvl screen while clicking quickly between "Clear Videos" -> "Attempt Videos" -> "Live Streams"

Using Chrome
![mom](https://cloud.githubusercontent.com/assets/19914470/16017775/653cd38e-316f-11e6-8eed-71a9e5c0534e.png)

**Comment by jaku** [comment]
Been aware of this. Just don't click so much. ;)

But seriously it's not super critical so low priority but thanks for making a ticket.

**Comment by FeFNiR104** [comment]
no worries :)

**Comment by triwave** [comment]
Easy fix, just added a flag to prevent multiple calls before prior is completed.  Will help a bit with server load too I presume.
