### ISSUE TITLE
UX/UI - Inconsistent and Conflicting Icons

### ISSUE THREAD

**Issue by SirDaev** [triwave/MakersofMario#38]
- The "Levels" link in the menu uses fa-gamepad while "Levels" under Website Stats uses fa-puzzle-piece. Recommendation: use fa-gamepad for both as it feels more suitable than fa-puzzle-piece.
- The same icon (fa-flag) is used for "Races" in the Menu and Stats, and for "Clears" in various views. Recommendation: Use fa-flag-checkered for "Races", or differentiate with color so that the icon for "Clears" is red and the icon for "Races" is not.

**Comment by triwave** [comment]
@SirDaev I agree with consistency.  It has certainly come a long way since the beta.

I will work towards unifying the approach with respect to both colors, icons and sizing.

**Comment by jaku** [comment]
all instances that didnt match should now be matching.
