### ISSUE TITLE
Redundant "Views" Link in Breadcrumbs

### ISSUE THREAD

**Issue by SirDaev** [triwave/MakersofMario#39]
The "View" link (/levels/view) in the breadcrumbs redirects to the same URL as the "Levels" link. Recommendation: Remove this as it is redundant and there is no viewable "View" view.

Related to [Issue #11](https://github.com/triwave/MakersofMario/issues/11)

**Comment by triwave** [comment]
Solid suggestion.

I have removed view from the breadcrumbs.
