### ISSUE TITLE
Bad Breadcrumbs Link in Profile View

### ISSUE THREAD

**Issue by SirDaev** [triwave/MakersofMario#40]
Example:
[GrandPooBear's Profile](https://makersofmario.com/new5222016/profiles/view/GrandPOOBear)
Clicking the username in Breadcrumbs results in:
_Something went wrong: profiles_controller does not respond to grandpoobear_

This is sitewide. It can also be achieved by attempting to navigate to any arbitrary profile name rather than it redirecting or throwing a 404.
Example:
[https://makersofmario.com/new5222016/profiles/notarealprofile](https://makersofmario.com/new5222016/profiles/notarealprofile)

Assuming this link should direct to the profile view, it requires <code>/view/</code> in the URL before the username.

Related to [Issue #39](https://github.com/triwave/MakersofMario/issues/39)?

**Comment by triwave** [comment]
Yeah, my apologies.  At work trying my best to split focus.

This should be working now, forgot to construct the href properly.

As for the 'not responding' error, you will still receive that when attempting to navigate to a non-existing route.  I will be redirecting the users properly in the future in those cases.
