### ISSUE TITLE
API - Worlds Created and Published without information are unsearchable and un-clickable

### ISSUE THREAD

**Issue by SirDaev** [triwave/MakersofMario#41]
Worlds can be Created and Published without a name (or any field input). This leads to the World being unsearchable and un-clickable in the User's profile. The only way to navigate to it (for edits and deletions) seems to be by manually entering the URL.

**Comment by jaku** [comment]
Will update API to disallow.

**Comment by aphex** [comment]
Latest API has updated to disallow empty names. This should also be caught on the front end and not allowed to be submitted.

@jaku please verify

**Comment by jaku** [comment]
Working. Thanks sir!
