### ISSUE TITLE
API - Duplicate worlds, levels and world bookmarks

### ISSUE THREAD

**Issue by jaku** [triwave/MakersofMario#42]
Duplicate names for different users is fine. But if I create world with the same name it should return an error and not create another world.

While we are in here, we should also remove the double levels or more I think we can see how that goes and if people hate it we can remove it.

And finally, it seems submitting multiple levels to get them all bookmarked at once is broken again. had to do quick workaround on the worlds page to send all the codes one after another.

**Comment by aphex** [comment]
Duplicate names per user are now disallowed
Duplicate levels are currently allowed TBD

Mutli-level bookmarking is confirmed working locally. 

@jaku please verify

**Comment by jaku** [comment]
All is working as mentioned. Will close and bring up the duplicate levels again later.
