### ISSUE TITLE
BUG - Level Creator user-name is being incorrectly parsed

### ISSUE THREAD

**Issue by dastrn** [triwave/MakersofMario#45]
![image](https://cloud.githubusercontent.com/assets/992196/16172804/0548ee84-355e-11e6-86a6-eaccd1e5e0bc.png)

I bumped into this on this level: 001C-0000-0229-1DBB

Bug persisted on F5 and Ctrl-F5

I opened another of Carl's stages and found the same thing here: 0CA7-0000-01CC-03DE

I'm unable to reproduce with any other users, after 5 or 6 random clicks all producing the expected display.

tl;dr Carl broke it.

**Comment by dastrn** [comment]
I was able to reproduce the error for any of Poo's stages:

![image](https://cloud.githubusercontent.com/assets/992196/16173332/5615278e-356c-11e6-9257-ffa65cc70dfe.png)

90D4-0000-023B-AD4A

Checked 20 other stages by 20 other users, no problems.

I still blame Carl.

**Comment by jaku** [comment]
We are aware. This page is getting completely re-written so we aren't updating it just yet.
