### ISSUE TITLE
UI - Add easy to find links to "Add World"

### ISSUE THREAD

**Issue by chrismademe** [triwave/MakersofMario#48]
Took me a good 10 minutes before I noticed the "Create new world" link in amongst the filtering options for Worlds.

Would be good to have up in the navbar next to the profile dropdown maybe?

Great work though, site is looking good :)

**Comment by jaku** [comment]
Added it to the dropdown. for now. might reconsider moving it and redoing some nav but for now it should be easier for others!

**Comment by chrismademe** [comment]
Awesome :)
