### ISSUE TITLE
Bookmark  Cookie Linking/Bookmarking

### ISSUE THREAD

**Issue by jaku** [triwave/MakersofMario#6]
I believe both are caused by the same root issue. The CSRF-Token must be unique for each user and is causing issues.

**Comment by jaku** [comment]
When adding a cookie from Warp.World or manually, the cookie is able to grab the NNID and insert the NNID into the database. However the Cookie does not get updated and when manually added, users are unable to bookmark levels/worlds.

**Comment by aphex** [comment]
fixed @jaku please verify

**Comment by jaku** [comment]
Mostly fixed. Cookie is accepted, returns the NNID and inserts NNID into database. However cookie does not stay stored in the database. Manually entering cookie fixes issue.

**Comment by jaku** [comment]
Hmm cookie stopped getting accepted. Tested with 2 accounts. Still seems to be broken.

@aphex

**Comment by jaku** [comment]
Fixed!
