### ISSUE TITLE
Removing Worlds

### ISSUE THREAD

**Issue by triwave** [triwave/MakersofMario#7]
Explore the possibility of removing worlds from the site.

We have to take caution as this can cause orphaned records if we simply delete it.

**Comment by jaku** [comment]
Updated the alert box for deleting worlds. If the API that is updated follows traditional ways, this code is done and is active. Otherwise should only require minor changes.

**Comment by jaku** [comment]
Also added the alert for removing a level from the world list. The back end will need to handle the reorder for this.

**Comment by jaku** [comment]
removing worlds and levels from worlds is working now.
