### ISSUE TITLE
Adding the same level to a world multiple times.

### ISSUE THREAD

**Issue by MYCRAFTisbest** [triwave/MakersofMario#8]
You can add the same level to a world multiple times. It's probably not supposed to do that.

**Comment by jaku** [comment]
Plan to fix this original thought on this was "it's your level whatever" but future discussions led us to planning on dropping this.

**Comment by MYCRAFTisbest** [comment]
I mean, some people might like the feature. Adding a dialog that says something like "WOAH, this level is already part of this world! Are you sure you want to add it again?" would also be fine. I can see some people wanting to do a reverse progression... for some reason.

**Comment by jaku** [comment]
Nah, future ideas for the site make this fundamentally broken. A World shouldn't have dupes and if a player wants to play a level more than twice then they can choose so since we aren't forcing them to play in any order. This is in the timeline to get fixed.
